package com.faforever.server.integration.v2.client;

import com.faforever.server.annotations.V2ClientNotification;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotNull;

/**
 * Message sent from the client to the server informing it about army statistics.
 */
@Getter
@AllArgsConstructor
@V2ClientNotification
@NoArgsConstructor
class ArmyStatsClientMessage extends V2ClientMessage {

  public static final String TYPE_NAME = "armyStats";

  /** The JSON-representation of the army statistics as generated by the game. */
  @NotNull
  private String stats;
}
