package com.faforever.server.integration.v2.client;

import com.faforever.server.annotations.V2ClientRequest;
import com.faforever.server.integration.v2.server.LoginDetailsServerMessage;
import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotNull;

/**
 * Message sent from the client to the server in order to log in.
 */
@Getter
@AllArgsConstructor
@NoArgsConstructor
@V2ClientRequest(successResponse = LoginDetailsServerMessage.class)
class LoginClientMessage extends V2ClientMessage {

  public static final String TYPE_NAME = "login";

  /** The JWT containing the claims, usually issued by the API. */
  @NotNull
  private String jwt;

  /** The "unique ID" as generated by the unique ID executable. */
  @NotNull
  private String uniqueId;
}
