package com.faforever.server.integration.v2.client;

import lombok.AllArgsConstructor;
import lombok.Getter;

/**
 * Message sent from the client to the server in order to log in.
 */
@Getter
@AllArgsConstructor
class LoginClientMessage extends V2ClientMessage {
  /** The JWT containing the claims, usually issued by the API. */
  private String jwt;
  /** The "unique ID" as generated by the unique ID executable. */
  private String uniqueId;
}
