spring:
  datasource:
    url: jdbc:mysql://${DATABASE_ADDRESS}/${DATABASE_NAME}?useSSL=false
    name: faf-db
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    show-sql: false
  boot:
    admin:
      client:
        url: ${SPRING_BOOT_ADMIN_CLIENT_URL:http://faf-spring-boot-admin:8030}

logging:
  path: ${LOG_FILE_DIRECTORY:/tmp}

faf-server:
  jwt:
    secret: ${JWT_SECRET}
  ladder1v1:
    season: ${LADDER1V1_SEASON}
    last-maps-not-considered: ${LAST_MAPS_NOT_CONSIDER:2}
