package com.faforever.server.entity;

import com.faforever.server.game.GameVisibility;
import com.faforever.server.stats.ArmyStatistics;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.MapKey;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;

@Entity
@Table(name = "game_stats")
@EqualsAndHashCode(of = "id")
@Setter
@Getter
@ToString(of = {"id", "title"}, includeFieldNames = false)
public class Game {

  /**
   * A key-value map of gamespecific options, like {@code "PrebuiltUnits" -> "Off"}.
   */
  @Transient
  private final Map<String, Object> options;

  @Transient
  private final AtomicInteger desyncCounter;

  /**
   * Maps player IDs to army scores reported by this player.
   */
  @Transient
  private final Map<Integer, List<ArmyScore>> reportedArmyScores;

  /**
   * Maps player IDs to army outcomes reported by this player.
   */
  @Transient
  private final Map<Integer, List<ArmyOutcome>> reportedArmyOutcomes;

  @Transient
  private final List<ArmyStatistics> armyStatistics;

  /**
   * Returns the list of players who are currently connected to the game.
   */
  @Transient
  private final Map<Integer, Player> connectedPlayers;

  /**
   * Maps player IDs to key-value option maps, like {@code 1234 -> "Color" -> 1 }
   */
  @Transient
  private final Map<Integer, Map<String, Object>> playerOptions;

  /**
   * Maps AI names to key-value option maps, like {@code "AI: Rufus" -> "Color" -> 1 }
   */
  @Transient
  private final Map<String, Map<String, Object>> aiOptions;

  @Transient
  private final List<String> simMods;

  @Transient
  private Integer minRating;

  @Transient
  private Integer maxRating;

  /**
   * Due to "performance reasons" this ID isn't generated by the DB but by the software. I was <strong>not</strong> to
   * one who game up with this.
   */
  @Id
  @Column(name = "id")
  private Integer id;

  @Column(name = "startTime")
  private Timestamp startTime;

  @Column(name = "gameType")
  private VictoryCondition victoryCondition;

  /**
   * Foreign key to "featured mod", but since there's no constraint in the database yet, hope for the best.
   */
  @ManyToOne(optional = false, fetch = FetchType.LAZY)
  @JoinColumn(name = "gameMod")
  private FeaturedMod featuredMod;

  @ManyToOne(optional = false, fetch = FetchType.LAZY)
  @JoinColumn(name = "host")
  private Player host;

  @ManyToOne(optional = false, fetch = FetchType.LAZY)
  @JoinColumn(name = "mapId")
  private MapVersion map;

  @Column(name = "gameName")
  private String title;

  @Column(name = "validity")
  @Enumerated(EnumType.ORDINAL)
  private Validity validity;

  /**
   * Mapped by player ID. Meant to be set just before game start.
   */
  @OneToMany(mappedBy = "game", cascade = CascadeType.ALL)
  @MapKey(name = "id")
  private Map<Integer, GamePlayerStats> playerStats;

  @Transient
  private GameState state = GameState.INITIALIZING;

  @Transient
  private String password;

  /**
   * Since some maps are unknown by the server (e.g. in-develop versions from map creators), the literal map name
   * is kept.
   */
  @Transient
  private String mapName;

  @Transient
  private int maxPlayers;

  @Transient
  private boolean ratingEnforced;

  @Transient
  private GameVisibility gameVisibility;

  @Transient
  private boolean mutuallyAgreedDraw;

  public Game(int id) {
    this();
    this.id = id;
  }

  public Game() {
    playerOptions = new HashMap<>();
    options = new HashMap<>();
    aiOptions = new HashMap<>();
    reportedArmyScores = new HashMap<>();
    reportedArmyOutcomes = new HashMap<>();
    armyStatistics = new ArrayList<>();
    playerStats = new HashMap<>();
    simMods = new ArrayList<>();
    connectedPlayers = new HashMap<>();
    desyncCounter = new AtomicInteger();
    validity = Validity.RANKED;
    gameVisibility = GameVisibility.PUBLIC;
  }

  public void replaceArmyStatistics(List<ArmyStatistics> newList) {
    synchronized (armyStatistics) {
      armyStatistics.clear();
      armyStatistics.addAll(newList);
    }
  }

  /**
   * Returns an unmodifiable list of army statistics.
   */
  public List<ArmyStatistics> getArmyStatistics() {
    return Collections.unmodifiableList(armyStatistics);
  }

  public Game setState(GameState state) {
    GameState.verifyTransition(this.state, state);
    this.state = state;
    return this;
  }
}
